### ISSUE TITLE
Crafting GUI won't open

### ISSUE THREAD

**Issue by WenXin20** [Fuzss/visualworkbench#1]
`Minecraft v1.16.5`
`Forge v36.1.32`
`Visual Workbench v1.0.1`

When right-clicking the crafting table on my server, it does not open the gui and only swings the player's hand. The log prints out `Failed to create screen for menu type: visualworkbench:crafting`. I also have Fast Workbench and Crafting Tweaks installed.
[Latest.log](https://gist.github.com/WenXin20/85da5a74c5ca85189c0ce566c5e255bc)

**Comment by Fuzss** [comment]
Do you always run into this issue, or just sometimes?

**Comment by WenXin20** [comment]
It happened every time I tried to open a crafting bench, modded or vanilla.

**Comment by WenXin20** [comment]
I tried v1.0.2, but I am still getting the error `Failed to create screen for menu type: visualworkbench:crafting`

**Comment by Fuzss** [comment]
Hmm, that's odd. I definitely fixed an issues related to this, but seems like there's more than just one.

So does it work in singleplayer? What mods do you have installed?

**Comment by WenXin20** [comment]
I haven't tried singleplayer yet. Fast Workbench and Crafting Tweaks are the only two that I know of that modify benches. Maybe Trash Slot too.

**Comment by Fuzss** [comment]
But just in general, what other mods do you have installed? They don't necessarily need to modify crafting tables to be incompatible.

**Comment by Fuzss** [comment]
Simply trying Visual Workbench on it's own, and just with those three mods would be great, just for narrowing it down.

**Comment by Fuzss** [comment]
So were you able to test a little more? I did plenty of tests myself, but I'm still unable to reproduce this problem unfortunately.

**Comment by WenXin20** [comment]
I tested a few mods in my pack with it in a separate instance, but not all of them yet. I haven't found what causes it either yet. I'll try to look into it more.

**Comment by WenXin20** [comment]
By this point, I've made a new mod pack but have not run into this problem again, so I'll close this for now. :)
