### ISSUE TITLE
Updating from 1.18 version to 1.18.1 causes a crash on startup if you don't delete the config files first.

### ISSUE THREAD

**Issue by AnotherVagabond** [Fuzss/visualworkbench#10]
To clarify: I was using the 1.18 files on a 1.18.1 Forge install, which worked fine. However, once updating to the new 1.18.1 version of the mod, I got a crash during startup. Once I deleted the config file, that fixed the crash, but I just wanted to post this here in cast anybody else ran into a similar problem.

	Failure message: Visual Workbench (visualworkbench) encountered an error during the sided_setup event phase
		java.lang.NullPointerException: Registry Object not present: visualworkbench:crafting_table

(This also happened with Easy Magic with the same failure message, just let me know if you want me to post a report over there as well if you want a record of it for future reference.)

**Comment by Fuzss** [comment]
Would be great to get the full crash log (from .minecraft/crash-reports) and the corresponding log (from .minecraft/logs/latest.log). 
This looks like a pretty serious issue. Also getting the files for Easy Magic would be great.

**Comment by Fuzss** [comment]
Can you upload the debug.log file? It's in the same location as latest.log.

**Comment by AnotherVagabond** [comment]
Sorry, there is no debug.log anywhere, even in the other folders. The logs folder just has latest.log and all the backups.

**Comment by Fuzss** [comment]
This should be resolved with PuzzlesLib v.3.3.3 now.
