### ISSUE TITLE
Crafting preview wrong with recipes using NBTs

### ISSUE THREAD

**Issue by Crystal-Spider** [Fuzss/visualworkbench#11]
When you're trying to craft something in the crafting table and the recipe uses NBT to output the correct result, the preview of the crafting is without the NBTs and as such the default version of the item is displayed instead of the correct one.  
For example, try to craft invisibility arrows and you'll see that the preview displays a pink tipped arrow instead of a gray tipped one.

**Comment by Nyphet** [comment]
I encountered the bug in 1.18.2, I didn't check other versions

**Comment by Fuzss** [comment]
I'm only working on 1.19+, backporting is tedious and no fun at all. the fix is now live in v4.0.0 for 1.19.
