### ISSUE TITLE
[Crash]: Crash during server startup

### ISSUE THREAD

**Issue by ElChusky** [Fuzss/visualworkbench#12]
### Mod Loader (Required)

Fabric

### Minecraft Version (Required)

1.19

### Mod Version (Required)

4.0.0

### Notes (Required)

It crashed during server startup.
Because of that, there's no crash report, just latest.log.
Unfortunately im unable to retrieve the full stacktrace in the cmd.

### Crash Report (Required)

https://gist.github.com/ElChusky/28f7c2f16a2f58315f8d00a3ed8d2f26

### latest.log (Optional)

https://gist.github.com/ElChusky/28f7c2f16a2f58315f8d00a3ed8d2f26

**Comment by Fuzss** [comment]
Thanks, update Puzzles Lib to v4.0.17 to fix this.

**Comment by ElChusky** [comment]
Nice, its fixed. TY ur a genius
