### ISSUE TITLE
My server and game crash when i use the crafting table

### ISSUE THREAD

**Issue by OffKlk** [Fuzss/visualworkbench#13]
### Mod Loader (Required)

Forge

### Minecraft Version (Required)

1.16.5

### Mod Version (Required)

1.1.0

### Notes (Required)

1. Open the menu of the crafting table
2. Put a item in the crafting table
3. The game and server crash

### Crash Report (Required)

https://gist.github.com/OffKlk/62d477d558d9c6876af3816820205771#file-gistfile1-txt

**Comment by Fuzss** [comment]
Can you test this jar? It'll still crash, but at least it will tell me why.
[VisualWorkbench-v1.1.1a1-1.16.5.jar](https://cdn.discordapp.com/attachments/917550806922846299/1002974377727504445/VisualWorkbench-v1.1.1a1-1.16.5.jar)
I tested this quite a bit on a local server and everything worked fine...

**Comment by Fuzss** [comment]
No response.
