### ISSUE TITLE
[Bug]: Crafting GUI with VCT's crafting tables is absent

### ISSUE THREAD

**Issue by GoldenDarius** [Fuzss/visualworkbench#14]
### Mod Loader (Required)

Forge

### Minecraft Version (Required)

1.19

### Mod Version (Required)

4.0.0

### Notes (Required)

I have both Visual Workbench and Variant Crafting Tables (1.6.2) installed, but despite the config of Visual Workbench indicating that the Crafting tables from that mod are supported, upon right-clicking on any of their Crafting tables, nothing happens.

**Comment by GoldenDarius** [comment]
Update: this issue seems to happen only when the flat crafting option is enabled

**Comment by Fuzss** [comment]
Fixed a while ago actually, closing this now.
