### ISSUE TITLE
[Suggestion]: Re-implement crouch+R-Click to place

### ISSUE THREAD

**Issue by SylisMC** [Fuzss/visualworkbench#16]
### Suggestion (Required)

Normally you can crouch+R-click on any interactable block to ignore the interaction and use the item in your hand as if the interactable block was any other normal block (e.g. Shift right-clicking a chest to place a hopper instead of opening it)

**Comment by TheonlyTazz** [comment]
is this issue going to get worked on? seeing how Taco also provided a PR for this issue.
would be great to implement this in our upcoming modpack @Fuzss

**Comment by Fuzss** [comment]
Fixed in v4.2.1.
