### ISSUE TITLE
[Bug]: My game is not opening

### ISSUE THREAD

**Issue by megachip1** [Fuzss/visualworkbench#18]
### Mod Loader (Required)

Forge

### Minecraft Version (Required)

1.19.2

### Mod Version (Required)

v4.2.0

### Notes (Required)

My game is not opening when i did instaled that mod, i tried evrything but nothing works.

**Comment by Fuzss** [comment]
Please provide a log, otherwise I can’t help you. 

https://gist.github.com/Fuzss/866b384d353912986e37b17eeef7a285
