### ISSUE TITLE
[Suggestion]: Add an option in the config to make items face a single direction no matter where you look at them.

### ISSUE THREAD

**Issue by HereToSaySomething** [Fuzss/visualworkbench#19]
### Suggestion (Required)

I do not like how the items always move to face you, almost as if they have a mind of their own. Can you add an option in the config where they just lock into one place and stay there? It would also be very nice if the direction it stays is where you were facing when you put the items on the crafting table. Here's what I mean visually speaking:
![image](https://user-images.githubusercontent.com/79809777/197610941-3f54534c-1498-4215-9aca-b9ed275c596e.png)
![image](https://user-images.githubusercontent.com/79809777/197611001-5690fb28-aa8f-4461-9b7c-9bab53a85e99.png)

**Comment by Fuzss** [comment]
Added for 1.19.3+.

**Comment by Aceplante2** [comment]
please add to 1.18.2
