### ISSUE TITLE
[Suggestion]: Use tag discovery instead of hardcoded list

### ISSUE THREAD

**Issue by natrow** [Fuzss/visualworkbench#22]
### Suggestion: Use tag discovery instead of hardcoded list

Could the config for enabling/disabling modded workbenches be moved into a block tag? 

Data packs have a lot of advantages over config files

**Comment by Fuzss** [comment]
Valid block entity block types need to be registered long before data packs are loaded, making this not easily possible without major changes to how block entities are handled. 

Also I don‘t see an advantage data packs would have over the config.
