### ISSUE TITLE
[Crash]: Caught exception during event FMLConstructModEvent dispatch for modid visualworkbench

### ISSUE THREAD

**Issue by Zemogiter** [Fuzss/visualworkbench#24]
### Mod Loader (Required)

Forge

### Minecraft Version (Required)

1.19.3

### Mod Version (Required)

v4.2.1-1.19.2-Forge

### Notes (Required)

Crash happens even when this mod is the only one in `mods` folder. Happens right after the loading screen and before the main menu. 

### Crash Report (Required)

https://github.com/Fuzss/visualworkbench/files/10449285/crash-2023-01-18_18.57.09-fml.txt

### latest.log (Optional)

https://github.com/Fuzss/visualworkbench/files/10449286/latest.log

**Comment by Fuzss** [comment]
1.19.3 isn't supported.
