### ISSUE TITLE
[Bug]: Comparators do not detect fill state 

### ISSUE THREAD

**Issue by LinuxSBC** [Fuzss/visualworkbench#25]
### Mod Loader (Required)

Quilt

### Minecraft Version (Required)

1.19.2

### Mod Version (Required)

v4.2.1

### Notes (Required)

Current behavior: Comparators detect nothing and have no redstone output regardless of fill level.
Steps to reproduce: Fill up the crafting table, then place a comparator facing away from it.
Expected behavior: The comparator produces a redstone output between levels 0 and 9 depending on how many slots of the crafting table are filled.

I'll see if I can work on this myself, but I don't have a ton of time, and I have basically no experience with Minecraft modding.

**Comment by Fuzss** [comment]
This is actually intentional. I chose to disable any comparator/hopper interaction to avoid possible dupe glitches (with hoppers). 

What‘s your use case for comparator output here?

**Comment by LinuxSBC** [comment]
I see. My use case was to hopefully add the possibility of Carpet-like autocrafting where a comparator unlocks a hopper underneath once the table reaches a certain fill state. If that adds the possibility of duping, however, I understand why you do not want to add it.
