### ISSUE TITLE
[Bug]: Tetra incompatibility

### ISSUE THREAD

**Issue by thimblebird** [Fuzss/visualworkbench#26]
### Mod Loader (Required)

Forge

### Minecraft Version (Required)

1.19.2

### Mod Version (Required)

4.2.1

### Notes (Required)

you can't right click crafting tables with a [tetra](https://www.curseforge.com/minecraft/mc-mods/tetra) [hammer](https://tetra.fandom.com/wiki/Getting_Started#Creating_a_Workbench)

**Comment by Fuzss** [comment]
Fixed in the latest version for 1.19.2.
