### ISSUE TITLE
[Bug]: Failed to create screen for menu type: visualworkbench:crafting

### ISSUE THREAD

**Issue by akharding91** [Fuzss/visualworkbench#27]
### Mod Loader (Required)

Forge

### Minecraft Version (Required)

1.19.2

### Mod Version (Required)

4.2.2

### Notes (Required)

Loaded game, opened single player LAN for other player who then joined, went to use the crafting table after placing dirt for a while as i needed to craft more spruce fences, crafting table menu wouldn't open, placed another crafting table to try and use that, after clicking back and forth between the two tables it glitched another crafting table into world, confused i checked MultiMC Launcher log, when i found the error, both players exited the world & I will try and reload pc/world to hopefully fix the problem. 

Sent a log in case this is a problem you need to know about. it might be a weird one time bug, as we have never had this happen before.

~ Using ~
Minecraft version: 1.19.2
Forge version: 43.2.6
Mod version: 4.2.2

### latest.log (Optional)

https://gist.github.com/akharding91/21f53b76fe6f11c70cd39b6042ee882d

**Comment by akharding91** [comment]
restarting/reloading the pc/world seems to have fix the problem for me at the moment. I have no clue what caused the bug, the glitched crafting table turned out to be a second one from my inventory as the one i was carrying at the time of exit was missing when I loaded up the world from my inventory but still placed in the world.

**Comment by Fuzss** [comment]
This sounds like a desync issue, not much that can be done.

**Comment by akharding91** [comment]
okay, feel free to mark this as closed then.
