### ISSUE TITLE
[Bug]: Optifine Compatablilty

### ISSUE THREAD

**Issue by MelrikBirchJr** [Fuzss/visualworkbench#28]
### Mod Loader (Required)

Forge

### Minecraft Version (Required)

1.19.2

### Mod Version (Required)

VisualWorkbench-v4.2.3-1.19.2-Forge

### Notes (Required)

VisualWorkbench-v4.2.3-1.19.2-Forge crashes when trying to use Optifine and im also confused cause it worked before if im not mistaken unless its incompatable due to issues with graphics? also there isnt a crash log since the game doesnt try to open after pressing play and it just says game has crashed no logs found but ive been testing which mod is the cause so i know its this one since its also a fabric mod and a forge mod but fabric doesnt support optifine without extra mod

**Comment by Fuzss** [comment]
I'm using the mod myself on Forge 1.19.2 with OptiFine and it works fine. Your explanation regarding the Fabric version doesn't make sense.
