### ISSUE TITLE
Duplicating items

### ISSUE THREAD

**Issue by Spus1** [Fuzss/visualworkbench#3]
If your friend opens crafting table, put items in it, and you grab the items from recipe grid back, the result in your friend's gui doesn't dissapier. That means that your friend can put items in, you grab the items back and he grabs the result item back. Boom! Duplicating. Pls fix that problem :)

**Comment by Trinsdar** [comment]
[here](https://i.imgur.com/RJ1ilsV.mp4)'s a video of the bug

**Comment by Trinsdar** [comment]
fyi I found out I have the same exact bug in my mod, I'll let you know how I solve it

**Comment by Trinsdar** [comment]
ok @Fuzss yhis is how I fixed it: https://github.com/Trinsdar/GT-4-Reimagined/commit/85ec1c481b8685b0993b88469834d49918a435ac

**Comment by Fuzss** [comment]
Fixed in v1.0.4.
