### ISSUE TITLE
[Suggestion]: Add compatibility for Variant Crafting Tables: Biome Makeover, Regions Unexplored, Nether's Exoticism, etc.

### ISSUE THREAD

**Issue by Numerosityy** [Fuzss/visualworkbench#36]
Add compatibility for Variant Crafting Tables: Biome Makeover, Regions Unexplored, Nether's Exoticism, etc.

Block ids are listed here:
Misc:
"vct:congealed_crafting_table",
"vct:echo_crafting_table",
"vct:ebony_crafting_table",
"vct:pream_crafting_table",
"vct:verdant_crafting_table",
"vct:jaboticaba_crafting_table",
"vct:ramboutan_crafting_table",

Biome Makeover:
"vct:bm_ancient_oak_crafting_table",
"vct:bm_blighted_balsa_crafting_table",
"vct:bm_swamp_cypress_crafting_table",
"vct:bm_willow_crafting_table",

Regions Unexplored:
"vct:rue_baobab_crafting_table",
"vct:rue_blackwood_crafting_table",
"vct:rue_cherry_crafting_table",
"vct:rue_cypress_crafting_table",
"vct:rue_dead_crafting_table",
"vct:rue_eucalyptus_crafting_table",
"vct:rue_joshua_crafting_table",
"vct:rue_larch_crafting_table",
"vct:rue_maple_crafting_table",
"vct:rue_mauve_crafting_table",
"vct:rue_palm_crafting_table",
"vct:rue_pine_crafting_table",
"vct:rue_redwood_crafting_table",
"vct:rue_willow_crafting_table"

**Comment by Fuzss** [comment]
thanks, added in v6.0.1.
