### ISSUE TITLE
Crashing Client on Server

### ISSUE THREAD

**Issue by SharkieTV** [Fuzss/visualworkbench#5]
Version 1.17.1
Client Crashes on Server with Visual Workbench on Client Side and Removed Server Side. 
Crashes when placing Crafting table.

Crash - https://pastebin.com/ehn0Emw7

**Comment by Fuzss** [comment]
Yeah so as mentioned on discord the mod has a pretty important server-side component as well, meaning it must be installed on both client and server... 😅
