### ISSUE TITLE
[Suggestion]: advertise quilt support on modrinth 

### ISSUE THREAD

**Issue by CuteistCat** [Fuzss/visualworkbench#50]
### Mod Loader (Optional)

Quilt

### Suggestion (Required)

Judging by the fact that quilt is listed as a modloader in the bug report form its probly supported so on modrinth you should check quilt support

**Comment by Fuzss** [comment]
The mod is developed for Fabric and not tested on Quilt. If it works it works, if it doesn’t it doesn’t.
