### ISSUE TITLE
[Crash]: Initializing minecraft with VisualWorkbench

### ISSUE THREAD

**Issue by RodrigoMG2406** [Fuzss/visualworkbench#53]
### Mod Loader (Required)

Forge

### Minecraft Version(s) (Required)

1.20.1

### Mod Version(s) (Required)

v8.0.0

### Other Mods Involved (Required)

Yes

### Notes (Required)

While checking for mod compatibility when VisualWorckbench is added with the rest of my other mods the game crashes when initializing.

### Crash Report (Required)

https://gist.github.com/RodrigoMG2406/9cd4d3cc23eea2793f14af3a9cd02e13

### latest.log (Optional)

https://gist.github.com/RodrigoMG2406/7a42e60849b6c3bf6abb3a6c253d0750

**Comment by Fuzss** [comment]
Please report this here: https://www.curseforge.com/minecraft/mc-mods/item-production-lib
