### ISSUE TITLE
[Bug]: unable to open, break and.. 

### ISSUE THREAD

**Issue by KonstaVilkman** [Fuzss/visualworkbench#55]
### Mod Loader (Required)

Fabric

### Minecraft Version(s) (Required)

1.20.4

### Mod Version(s) (Required)

v20.4.1-1.20.4-Fabric

### Other Mods Involved (Required)

No

### Notes (Required)

Shows up when right clicking the workbench. Still opens the workbench but visuals do not work and functions the same as the normal workbench

### latest.log (Required)

-

**Comment by KonstaVilkman** [comment]
![image](https://github.com/Fuzss/visualworkbench/assets/73310940/51371b7d-7216-4046-b542-829b004828e8)

Works fine in singleplayer but not multiplayer (the mod is installed on the server side)

**Comment by KonstaVilkman** [comment]
![image](https://github.com/Fuzss/visualworkbench/assets/73310940/3e12a3c9-0b76-4811-b78e-633b92c0d5a1)

**Comment by Fuzss** [comment]
Upload latest.log

**Comment by Fuzss** [comment]
From both server and client. It‘s possible this is caused by an outdated version of Fabric Api.

**Comment by KonstaVilkman** [comment]
[latest.log](https://github.com/Fuzss/visualworkbench/files/14625163/latest.log)
Client ^^
[latest.log](https://github.com/Fuzss/visualworkbench/files/14625166/latest.log)
server ^^

I'll double check the fabric api. Its weird cuz I just threw all the same mods into the server mods folder

**Comment by KonstaVilkman** [comment]
Update. Nothing of my server sided mods are working... For some reason. And ofc no config file generated wth is this.

**Comment by KonstaVilkman** [comment]
okay I just suck. It was my fault. I had accidentally messed up the server installation. (fabric somehow it was just the default mc server.jar even tho I installed it with the fabric installer.
