### ISSUE TITLE
[1.16.5] Shift+left click not working with 1.0.4 & 1.0.5

### ISSUE THREAD

**Issue by zISKo666** [Fuzss/visualworkbench#6]
Hello,

When filling a crafting table with 3x3 full 64 item stack gold ingots for example, you only get one gold block when click the output slot even with shift+left click.
This happens with 1.0.4 & 1.0.5.
So I downgraded to 1.0.3 which is working like expected.

Tested with Visualworkbench only on Forge 36.2.19

Kind regards
zISKo

**Comment by Fuzss** [comment]
Fixed in v1.0.6. Thank's a lot for reporting!
