### ISSUE TITLE
[Bug]: Visual workbench, easy anvil and magic's respective blocks all turn into the stone block when placed, although they can still be interacted with.

### ISSUE THREAD

**Issue by cobaltlol2** [Fuzss/visualworkbench#62]
### Mod Loader (Required)

Fabric

### Minecraft Version(s) (Required)

1.21

### Mod Version(s) (Required)

v21.0.1 (workbench), v21.0.2 (easy anvil), v21.0.1 (easy magic)

### Other Mods Involved (Required)

No

### Notes (Required)

![image](https://github.com/Fuzss/visualworkbench/assets/174870492/584cf9cf-66dd-4aaf-bbdd-8413c07e991c)
In the image attached, you can see the respective blocks placed alongside eachother in a stone block form.

### latest.log (Required)

https://gist.github.com/cobaltlol2/554559ce74468d53fd5d76e34b5122f1

**Comment by cobaltlol2** [comment]
Oops mb meant to put yes for other mods involved, it stops happening when I remove all mods except these 3 and their dependancies.

**Comment by Fuzss** [comment]
Could you possibly do some more tests with subset of your mods to find which one is conflicting?

FerriteCore, ModernFix and Sodium would be some suspects.

**Comment by cobaltlol2** [comment]
> Could you possibly do some more tests with subset of your mods to find which one is conflicting?
> 
> FerriteCore, ModernFix and Sodium would be some suspects.

Modernfix looks like it was responsible as it stopped happening when I removed it, could it be a config problem or something?

**Comment by mpustovoi** [comment]
Perhaps this is because the ModernFix's `mixin.perf.dynamic_resources` option is enabled.
This option greatly speeds up the loading of my Minecraft instances.

**Comment by Fuzss** [comment]
Yes, disabling that option is a temporary solution until I'm able to provide a proper fix.

**Comment by Fuzss** [comment]
Fixed by updating Puzzles Lib to v21.0.20.
