### ISSUE TITLE
[Suggestion]: I open the server with the server opening program, but the server does not close with the STOP command.

### ISSUE THREAD

**Issue by pil0lo** [Fuzss/visualworkbench#63]
### Mod Loader (Optional)

Fabric

### Minecraft Version(s) (Optional)

1.21

### Suggestion (Required)

It works well in single player.
Even if I open the server it works fine.
However, when I close the server, it stops in place as shown in the picture and does not close completely.

VisualWorkbench-v21.0.1-1.21-Fabric / PuzzlesLib-v21.0.9-1.21-Fabric / ForgeConfigAPIPort-v21.0.1-1.21-Fabric
If you remove this mode, the server will close normally.

Server program : https://server-engine.kr/

![1](https://github.com/Fuzss/visualworkbench/assets/143984023/80e80231-b88f-4f14-8079-c383c545ca12)

**Comment by Fuzss** [comment]
Follow these steps: 
https://gist.github.com/Fuzss/9692f6ed5e8cca485a58004c28c9045b
https://gist.github.com/Fuzss/866b384d353912986e37b17eeef7a285

**Comment by pil0lo** [comment]
video
1. Excluding all modes
2. Add only the modes you use.
3. Insert the corresponding mode
I took a video.
Using 1 and 2 will cause the server to shut down gracefully.
Even if the server is shut down three times, the time the server is open continues to pass.

Problem video sequence 1. Excluding all modes 2. Add only the modes you use. 3. Listed in order of Insert the corresponding mode.
youtube video : https://youtu.be/9bl5mBJp1PI

[latest.log](https://github.com/user-attachments/files/16138595/latest.log)

**Comment by Fuzss** [comment]
Looking at your screenshot above the server seems to be shutting down without issues after having received a stop command. Visual Workbench is simply unloading the configs. There appears to be no issue here.

**Comment by pil0lo** [comment]
If you reopen the server with that program, you will need to restart and reopen the computer because it indicates that the file is already in use.
You must restart your computer before you can reopen the server.
I think I'll just have to do it.
Thank you for your answer.

**Comment by Fuzss** [comment]
The issue is unrelated to Visual Workbench. The unloading task is simply the last task able to complete before the server hangs.
