### ISSUE TITLE
[Bug]: Axe not breaking workbench faster

### ISSUE THREAD

**Issue by Proxi2** [Fuzss/visualworkbench#64]
### Mod Loader (Required)

Fabric

### Minecraft Version(s) (Required)

1.21

### Mod Version(s) (Required)

v21.0.1

### Other Mods Involved (Required)

Yes

### Notes (Required)

So when I'm in the server I'm hosting and I go to break one of the visual workbenches with an axe, it doesn't break faster (and doesn't show an axe icon on WTHIT). I went into singleplayer to check if it was like that there too and it's not. It works just like a normal crafting table. I looked in the logs and the only thing I found that may be related is "Reference map 'visualworkbench.fabric.refmap.json' for visualworkbench.fabric.mixins.json could not be read. If this is a development environment you can ignore this message" but there's nothing else about visual workbench that seems off.

In singleplayer you can clearly see the axe icon at the bottom right indicating that it'll break faster with it
![image](https://github.com/Fuzss/visualworkbench/assets/113284957/0ca40530-ec94-4bf2-93c4-ab74bc20a825)

But on the server it doesn't have that icon and definitely doesn't break faster with an axe
![image](https://github.com/Fuzss/visualworkbench/assets/113284957/98db3ea1-9037-43a0-b610-79c6ac2c4ced)

Both are with the same exact mods and configs. The only difference is that one is singleplayer and the other is a multiplayer server. I have no clue why this would happen. I can give you anything else you need to help out, and I attached the full log file for the server up to where people started joining. Any help would be appreciated. Its such a simple mechanic that I have very much taken for granted until now

### latest.log (Required)

https://gist.github.com/Proxi2/00a8ea52494d0bfcd4a50c245cb0cc14

**Comment by Proxi2** [comment]
I've just discovered that I have the same problem with the Easy Anvil and Easy Magic, though you still need to use a pickaxe for the anvil or the enchant table to drop when you break it. Just adding this in case it helps narrow down what the problem might be

**Comment by Fuzss** [comment]
#67
