### ISSUE TITLE
[Bug]: Issue with More Smithing Tables mod

### ISSUE THREAD

**Issue by SabsRat** [Fuzss/visualworkbench#66]
### Mod Loader (Required)

Fabric

### Minecraft Version(s) (Required)

1.21

### Mod Version(s) (Required)

VisualWorkbench-v21.0.1-1.21-Fabric

### Other Mods Involved (Required)

Yes

### Notes (Required)

![image 2](https://github.com/user-attachments/assets/ee7187f2-fedc-47c4-a2bb-8b0de286cde7)
![image](https://github.com/user-attachments/assets/c85417fb-3ce1-4da7-8aab-023618baabc1)
the og smithing table works fine its the varients in this mod that act like a crafting table
MoreSmithingTables-1.0.0+1.21-Fabric is the mod

### latest.log (Required)

<script src="https://gist.github.com/SabsRat/ccce5ad795b1112eb9aa21c851469a12.js"></script>

**Comment by SabsRat** [comment]
it was on there end so its resolved

**Comment by SabsRat** [comment]
it was on their end so its resolved

**Comment by Fuzss** [comment]
Smithing Tables are implemented as crafting tables in vanilla for some reason. But mods can opt out of having their blocks be changed by Visual Workbench.

**Comment by pnk2u** [comment]
> Smithing Tables are implemented as crafting tables in vanilla for some reason. But mods can opt out of having their blocks be changed by Visual Workbench.

Yeah, I added them to the unaltered_workbenches tag, I assume that is the intended way.
If so and I'm not overlooking something, I wish this was communicated somewhere on the mod's description page, maybe as part of the faq page.
