### ISSUE TITLE
[Bug]: Crafting Tables No Longer Break Faster With Correct Tool

### ISSUE THREAD

**Issue by bettskyrin** [Fuzss/visualworkbench#67]
### Mod Loader (Required)

Fabric

### Minecraft Version(s) (Required)

1.21

### Mod Version(s) (Required)

v21.0.1

### Other Mods Involved (Required)

Yes

### Notes (Required)

Crafting tables (as well as anvils) that have been re-placed do not have their mining speeds altered by using the correct tool.

### latest.log (Required)

https://mclo.gs/Uoy2Cqx

**Comment by Fuzss** [comment]
Fixed in v21.0.3.
