### ISSUE TITLE
more mod compatible

### ISSUE THREAD

**Issue by AlleCraft-alterego** [Fuzss/visualworkbench#9]
i have add this workbench in config but not work, can be possible add compatible ?

   - craftingautomat:autocrafter
   - cyclic:workbench
   - cyclic:crafter
   - prettypipes:crafting_terminal
   - immersiveengineering:craftingtable
   - essentials:autocrafter

**Comment by Fuzss** [comment]
Those crafting tables do not seem to extend vanilla crafting tables. Supporting them is out of scope for this mod, sorry.
